"""add globus transfer support

Revision ID: 77634f601943
Revises: 0.9.6
Create Date: 2026-06-24 18:33:27.614942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77634f601943'
down_revision = '0.9.6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('globus_storage',
    sa.Column('origin_id', sa.String(length=36), nullable=False),
    sa.Column('origin_path', sa.Text(), nullable=False),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('sha', name=op.f('pk_globus_storage')),
    sa.UniqueConstraint('origin_id', 'origin_path', name='uq_globus_storage_origin_path')
    )
    op.create_table('globus_transfer',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAILED', 'SUCCEEDED', name='globustransferstatus'), nullable=False),
    sa.Column('completion_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_globus_transfer'))
    )
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('globus_storage_sha', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('globus_transfer_task_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_file_globus_transfer_task_id_globus_transfer'), 'globus_transfer', ['globus_transfer_task_id'], ['task_id'])
        batch_op.create_foreign_key(batch_op.f('fk_file_globus_storage_sha_globus_storage'), 'globus_storage', ['globus_storage_sha'], ['sha'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_file_globus_storage_sha_globus_storage'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_file_globus_transfer_task_id_globus_transfer'), type_='foreignkey')
        batch_op.drop_column('globus_transfer_task_id')
        batch_op.drop_column('globus_storage_sha')

    op.drop_table('globus_transfer')
    op.drop_table('globus_storage')
    # ### end Alembic commands ###
